const data = {
    albums: [
        {
            AlbumID: '3778',
            ArtistID: '123427',
            artists: 'Blur',
            AlbumTitle: '13',
            Genre: 'Rock',
            copiesOnHand: '19',
            AlbumRelease: '1999-03-15 00:00:00',
            AlbumCost: '19.99',
            TrackAmount: '13',
            ProducerFName: 'William',
            ProducerLName: 'Orbit',
            InPrint: '1',
            image: '/Images/Covers/13.jpg',
            rating: '4.5',
            numReviews: '10',
        },
        {
            AlbumID: '1177',
            ArtistID: '123456',
            artists: 'Brian Eno',
            AlbumTitle: 'Taking Tiger Mountain',
            Genre: 'Experimental',
            copiesOnHand: '15',
            AlbumRelease: '1974-11-01 00:00:00',
            AlbumCost: '9.00',
            TrackAmount: '10',
            ProducerFName: 'Brian',
            ProducerLName: 'Eno',
            InPrint: '1',
            image: '/Images/Covers/TakingTigerMountain.jpg',
            rating: '4.5',
            numReviews: '10',
        },
        {
            AlbumID: '3677',
            ArtistID: '123587',
            artists: 'CAN',
            AlbumTitle: 'Tago Mago',
            Genre: 'Experimental',
            copiesOnHand: '0',
            AlbumRelease: '1971-02-01 00:00:00',
            AlbumCost: '6.99',
            TrackAmount: '7',
            ProducerFName: 'The band',
            ProducerLName: 'CAN',
            InPrint: '1',
            image: '/Images/Covers/TagoMago.jpg',
            rating: '5',
            numReviews: '10',
        },
        {
            AlbumID: '7778',
            ArtistID: '123466',
            artists: 'David Bowie',
            AlbumTitle: 'Low',
            Genre: 'Rock',
            copiesOnHand: '11',
            AlbumRelease: '1977-01-14 00:00:00',
            AlbumCost: '10.00',
            TrackAmount: '10',
            ProducerFName: 'Tony',
            ProducerLName: 'Visconti',
            InPrint: '1',
            image: '/Images/Covers/Low.jpg',
            rating: '5',
            numReviews: '10',
        },
        {
            AlbumID: '1277',
            ArtistID: '123417',
            artists: 'Frank Zappa',
            AlbumTitle: 'Lumpy Gravy',
            Genre: 'Experimental',
            copiesOnHand: '5',
            AlbumRelease: '1967-08-07 00:00:00',
            AlbumCost: '5.00',
            TrackAmount: '5',
            ProducerFName: 'Frank',
            ProducerLName: 'Zappa',
            InPrint: '1',
            image: '/Images/Covers/LumpyGravy.jpg',
            rating: '4.5',
            numReviews: '10',
        },

    ],
};

export default data;
